apiVersion: v1
kind: BuildConfig
metadata:
  name: exampleservice-pipeline-ci
  labels:
    service: exampleservice
    type: pipeline
    scope: ci
  annotations:
    pipeline.alpha.openshift.io/uses: '[{"name": "exampleservice", "namespace": "", "kind": "DeploymentConfig"}]'
spec:
  source:
    git:
      ref: master
      uri: https://github.com/TPX01/example.k8s.service.git
      type: Git
  strategy:
    type: JenkinsPipeline
    jenkinsPipelineStrategy:
      jenkinsfilePath: Jenkinsfile
  triggers:
    - type: GitHub
      github:
        secret: UhcUH5Em
  runPolicy: Serial
  output:
  resources:
  postCommit:
