apiVersion: v1
kind: BuildConfig
metadata:
  name: pet-service-pipeline
  labels:
    service: pet
    type: pipeline
  annotations:
    pipeline.alpha.openshift.io/uses: '[{"name": "pet", "namespace": "", "kind": "DeploymentConfig"}]'
spec:
  source:
    git:
      ref: master
      uri: https://github.com/TPX01/pet-service.git
      type: Git
  strategy:
    type: JenkinsPipeline
    jenkinsPipelineStrategy:
      jenkinsfilePath: Jenkinsfile
  triggers:
    - type: GitHub
      github:
        secret: UhcUH5Em
  runPolicy: Serial
  output:
  resources:
  postCommit:
